repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        files: ^backend/
        args: [--fix]
      - id: ruff-format
        files: ^backend/
  
  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--write"]  # Auto-format the files
        files: ^frontend/\.((js|jsx|ts|tsx|json|css|scss|md)$)

