repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        files: ^backend/
        args: [--fix]
      - id: ruff-format
        files: \.py$
  
  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--write"]  # Auto-format the files
        files: \.((js|jsx|ts|tsx|json|css|scss|md)$)

  - repo: local
    hooks:
      - id: py2ts
        name: py2ts
        language: system
        entry: scripts/py2ts.sh
        pass_filenames: false
        always_run: true
        

