FROM python:3.12 AS builder

RUN pip install uv
COPY ./uv.lock ./pyproject.toml ./
WORKDIR /app
RUN uv export --no-dev --format requirements-txt > requirements.txt

FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/requirements.txt ./
RUN pip install -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
