[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "sqlmodel>=0.0.22",
    "uvicorn[fastapi]>=0.34.0",
]

[dependency-groups]
dev = [
    "ipython>=8.32.0",
]
